### ISSUE TITLE
error on Gephi 0.10.1

### ISSUE THREAD

**Issue by jronallo** [JSiv/MultiViz#1]
I get this error when trying to run the plugin with Gephi 0.10.1:

[SEVERE] null 
java.lang.NoSuchMethodError: org.gephi.filters.plugin.partition.PartitionBuilder$NodePartitionFilter: method 'void <init>(org.gephi.appearance.api.Partition)' not found
	at multiviz.MultiLayerVisualization.goAlgo(MultiLayerVisualization.java:118)
	at org.gephi.layout.LayoutControllerImpl$LayoutRun.run(LayoutControllerImpl.java:196)
	at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.call(LongTaskExecutor.java:336)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by chhyunch** [comment]
Same as me.
Can not find on plugin tab.

**Comment by JSiv** [comment]
Hi,

Thank you for bringing this to our attention. Please note that the plugin currently supports Gephi 0.9.3, and we are actively working on making it compatible with Gephi 0.10.1 in the future.
